# Generated by Django 4.2.13 on 2024-05-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_organization',
            field=models.BooleanField(default=False),
        ),
    ]
