# Generated by Django 4.2.13 on 2024-05-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_organization_user_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='email',
        ),
    ]
