# Generated by Django 4.2.13 on 2024-05-25 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_organization_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Zahtev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.organization')),
            ],
        ),
    ]
