# Generated by Django 4.2.13 on 2024-05-25 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_organization_organization_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zahtev',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.organization'),
        ),
    ]
