# Generated by Django 4.2.13 on 2024-05-29 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oglas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
                ('stanje', models.IntegerField()),
                ('opis', models.TextField()),
                ('pol', models.CharField(choices=[('musko', 'musko'), ('zensko', 'zensko'), ('decije', 'decije')], max_length=6)),
                ('velicina', models.CharField(max_length=50)),
                ('vreme', models.DateTimeField(auto_now_add=True)),
                ('slika', models.ImageField(upload_to='oglasi/')),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sadrzi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oglas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oglasi.oglas')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oglasi.tag')),
            ],
        ),
        migrations.AddField(
            model_name='oglas',
            name='tagovi',
            field=models.ManyToManyField(through='oglasi.Sadrzi', to='oglasi.tag'),
        ),
    ]
